version: "3.7"
services:
  pow:
    image: ethereum/client-go
    restart: on-failure
    volumes:
      - ${RP_PATH}:/root
      - ./pow:/pow:ro
    networks:
      - net
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
      - "30305:30305"
    entrypoint: [sh, -c, "\
      /usr/local/bin/geth init /pow/genesis77.json && \
      /usr/local/bin/geth \
        --networkid 77 \
        --syncmode full \
        --bootnodes enode://6114b79e7928bfb19ff8600bad6e09a49cfc53f7d9513bb0e854566102ee04bac8f494472bcc812211c2cc50684f8a04320d23c17410b52c6175e8246b5a3307@3.216.221.20:30305 \
        --targetgaslimit 8000000 \
        --rpc \
        --rpcaddr 0.0.0.0 \
        --rpcvhosts '*' \
    "]
  beacon:
    image: beacon-chain-simulator
    restart: on-failure
    volumes:
      - ${RP_PATH}:/.rocketpool
    networks:
      - net
    links:
      - pow
    ports:
      - "9545:9545"
    command: [
      "--powHost", "http://pow:8545",
      "--depositContract", "0xb8c763648c1f251006dd275662f6e7c8e2eb135a",
      "--withdrawalContract", "0x23104b8a290316a1708dde6dda1803d30b9cb833",
      "--from", "0x2f6812e7005c61835b12544eeb45958099ef45f4",
      "--database", "/.rocketpool/beacon.json"
    ]
  minipools:
    image: rocketpool-minipools
    restart: on-failure
    volumes:
      - ${RP_PATH}:/.rocketpool
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
    links:
      - pow
    command: [
      "${RP_PATH}",
      "rocketpool_net",
      "rocketpool_pow_1",
      "rocketpool_beacon_1",
    ]
  node:
    image: rocketpool-node
    restart: on-failure
    volumes:
      - ${RP_PATH}:/.rocketpool
    networks:
      - net
    links:
      - pow
  watchtower:
    image: rocketpool-watchtower
    restart: on-failure
    volumes:
      - ${RP_PATH}:/.rocketpool
    networks:
      - net
    links:
      - beacon
      - pow
networks:
  net:
