version: "3.7"
services:
  geth:
    image: ethereum/client-go
    volumes:
      - /Users/moles/.rocketpool:/root
    networks:
      - net
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
    command: [
      "--networkid", "11",
      "--targetgaslimit", "8000000",
      "--rpc",
      "--rpcaddr", "0.0.0.0",
      "--rpcvhosts", "geth",
      # Clique mining parameters
      "--mine",
      "--allow-insecure-unlock",
      "--unlock", "0xca00774c08c016dd831ee4c063c56eec4b9f928e",
      "--password", "/root/.ethereum/password"
    ]
  beacon:
    image: beacon-chain-simulator
    volumes:
      - /Users/moles/.rocketpool:/.rocketpool
    networks:
      - net
    links:
      - geth
    ports:
      - "9545:9545"
    command: [
      "--depositContract", "0x16EBaCb3cF1E1Bc2220335c606aeE3f1cFb1178c",
      "--withdrawalContract", "0x0BCa77f1202D9A6FA2aa0B6dDe9c822999134cA7",
      "--from", "0xca00774c08c016dd831ee4c063c56eec4b9f928e",
      "--database", "/.rocketpool/beacon.json"
    ]
  node:
    image: rocketpool-node
    volumes:
      - /Users/moles/.rocketpool:/.rocketpool
    networks:
      - net
    links:
      - geth
  watchtower:
    image: rocketpool-watchtower
    volumes:
      - /Users/moles/.rocketpool:/.rocketpool
    networks:
      - net
    links:
      - beacon
      - geth
networks:
  net:
