version: "3.7"
services:
  pow:
    image: ethereum/client-go
    restart: on-failure
    volumes:
      - eth1clientdata:/ethclient
      - ./pow:/pow:ro
    networks:
      - net
    entrypoint: [sh, -c, "\
      /pow/setup.sh geth 77 \
      enode://6114b79e7928bfb19ff8600bad6e09a49cfc53f7d9513bb0e854566102ee04bac8f494472bcc812211c2cc50684f8a04320d23c17410b52c6175e8246b5a3307@3.216.221.20:30305 \
      RP2Beta-Node \
      rp2testbeta@3.216.221.20 \
    "]
  beacon:
    image: rocketpool/beacon-chain-simulator:v0.0.1
    restart: on-failure
    volumes:
      - eth2clientdata:/ethclient
    networks:
      - net
    command: [
      "--powHost", "ws://pow:8546",
      "--depositContract", "0xb8c763648c1f251006dd275662f6e7c8e2eb135a",
      "--withdrawalContract", "0x23104b8a290316a1708dde6dda1803d30b9cb833",
      "--from", "0x2f6812e7005c61835b12544eeb45958099ef45f4",
      "--database", "/ethclient/beacon.json"
    ]
  minipools:
    image: rocketpool/smartnode-minipools:v0.0.1
    restart: on-failure
    volumes:
      - ${RP_PATH}:/.rocketpool
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
    command: [
      "${RP_PATH}",
      "${COMPOSE_PROJECT_NAME}_net",
      "${COMPOSE_PROJECT_NAME}_pow_1",
      "${COMPOSE_PROJECT_NAME}_beacon_1",
    ]
  node:
    image: rocketpool/smartnode-node:v0.0.1
    restart: on-failure
    volumes:
      - ${RP_PATH}:/.rocketpool
    networks:
      - net
  watchtower:
    image: rocketpool/smartnode-watchtower:v0.0.1
    restart: on-failure
    volumes:
      - ${RP_PATH}:/.rocketpool
    networks:
      - net
networks:
  net:
volumes:
  eth1clientdata:
  eth2clientdata:
