version: "3.7"
services:
  node:
    image: rocketpool-node
    volumes:
      - /Users/moles/.rocketpool:/.rocketpool
    networks:
      - net
  watchtower:
    image: rocketpool-watchtower
    volumes:
      - /Users/moles/.rocketpool:/.rocketpool
    networks:
      - net
networks:
  net:
