consensusCommon:
  apiPort: "5052"
  checkpointSyncUrl: ""
  doppelgangerDetection: "true"
  graffiti: ""
  maxPeers: "100"
  openApiPort: "false"
  p2pPort: "9001"
executionCommon:
  httpPort: "8545"
  openRpcPorts: "false"
  wsPort: "8546"
exporter:
  containerTag: prom/node-exporter:v1.3.1
  enableRootFs: "false"
  port: "9103"
externalExecution:
  httpUrl: ""
  wsUrl: ""
externalLighthouse:
  additionalVcFlags: ""
  containerTag: sigp/lighthouse:v2.1.3
  doppelgangerDetection: "true"
  graffiti: ""
  httpUrl: ""
externalPrysm:
  additionalVcFlags: ""
  containerTag: prysmaticlabs/prysm-validator:HEAD-e26cde-debug
  doppelgangerDetection: "true"
  graffiti: ""
  httpUrl: ""
  jsonRpcUrl: ""
externalTeku:
  additionalVcFlags: ""
  containerTag: consensys/teku:22.1.1
  doppelgangerDetection: "true"
  graffiti: ""
  httpUrl: ""
fallbackExecutionCommon:
  httpPort: "8545"
  openRpcPorts: "false"
  wsPort: "8546"
fallbackExternalExecution:
  httpUrl: ""
  wsUrl: ""
fallbackInfura:
  additionalFlags: ""
  containerTag: rocketpool/smartnode-pow-proxy:1.3.0-dev
  projectID: ""
fallbackPocket:
  additionalFlags: ""
  containerTag: rocketpool/smartnode-pow-proxy:1.3.0-dev
  gatewayID: lb/613bb4ae8c124d00353c40a1
geth:
  additionalFlags: ""
  cache: "16384"
  containerTag: ethereum/client-go:v1.10.15
  ethstatsLabel: ""
  ethstatsLogin: ""
  maxPeers: "50"
  p2pPort: "30303"
grafana:
  containerTag: grafana/grafana:8.3.2
  port: "3100"
infura:
  additionalFlags: ""
  containerTag: rocketpool/smartnode-pow-proxy:1.3.0-dev
  projectID: ""
lighthouse:
  additionalBnFlags: ""
  additionalVcFlags: ""
  containerTag: sigp/lighthouse:v2.1.3
nimbus:
  additionalFlags: ""
  containerTag: statusim/nimbus-eth2:multiarch-v1.7.0
pocket:
  additionalFlags: ""
  containerTag: rocketpool/smartnode-pow-proxy:1.3.0-dev
  gatewayID: lb/613bb4ae8c124d00353c40a1
prometheus:
  containerTag: prom/prometheus:v2.31.1
  openPort: "false"
  port: "9091"
prysm:
  additionalBnFlags: ""
  additionalVcFlags: ""
  bnContainerTag: prysmaticlabs/prysm-beacon-chain:HEAD-e26cde-debug
  openRpcPort: "false"
  rpcPort: "5053"
  vcContainerTag: prysmaticlabs/prysm-validator:HEAD-e26cde-debug
root:
  bnMetricsPort: "9100"
  consensusClient: nimbus
  consensusClientMode: local
  enableMetrics: "false"
  executionClient: geth
  executionClientMode: local
  exporterMetricsPort: "9103"
  externalConsensusClient: lighthouse
  fallbackExecutionClient: pocket
  fallbackExecutionClientMode: local
  nodeMetricsPort: "9102"
  reconnectDelay: 60s
  useFallbackExecutionClient: "false"
  vcMetricsPort: "9101"
  watchtowerMetricsPort: "9104"
smartnode:
  manualMaxFee: "0"
  minipoolStakeGasThreshold: "150"
  network: mainnet
  passwordPath: $HOME/.rocketpool/data
  priorityFee: "2"
  projectName: rocketpool
  rplClaimGasThreshold: "150"
  validatorRestartCommand: $HOME/.rocketpool/chains/eth2/restart-validator.sh
teku:
  additionalBnFlags: ""
  additionalVcFlags: ""
  containerTag: consensys/teku:22.1.1
